
name: Build and Run Helloworld

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc-14

    - name: Build helloworld.cpp
      run: gcc-14 -o helloworld helloworld.cpp

    - name: Run helloworld
      run: ./helloworld

    - name: report compiler version
      run: gcc-14 --version