
name: Build and Run Helloworld

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc-14

    - name: install ACfL
      run: curl -L https://developer.arm.com/-/cdn-downloads/permalink/Arm-Compiler-for-Linux/Package/install.sh -o /tmp/install.sh && sudo /tmp/install.sh --i-agree-to-the-contained-eula --accept --no-interactive

    - name: Build helloworld.c with gcc
      run: gcc-14 -o helloworld.gcc helloworld.c

    - name: Run helloworld.gcc
      run: ./helloworld.gcc

    - name: Build helloworld.c with ACfL
      run: armclang -o helloworld.acfl helloworld.c

    - name: Run helloworld with ACfL
      run: ./helloworld.acfl

    - name: report compiler version
      run: gcc-14 --version